
package soap_alimail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webservice", targetNamespace = "http://soap_alimail/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Webservice {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "check", targetNamespace = "http://soap_alimail/", className = "soap_alimail.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://soap_alimail/", className = "soap_alimail.CheckResponse")
    @Action(input = "http://soap_alimail/webservice/checkRequest", output = "http://soap_alimail/webservice/checkResponse")
    public void check(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "send_mail")
    @RequestWrapper(localName = "send_mail", targetNamespace = "http://soap_alimail/", className = "soap_alimail.SendMail")
    @ResponseWrapper(localName = "send_mailResponse", targetNamespace = "http://soap_alimail/", className = "soap_alimail.SendMailResponse")
    @Action(input = "http://soap_alimail/webservice/send_mailRequest", output = "http://soap_alimail/webservice/send_mailResponse")
    public void sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod(operationName = "BatchSendMail")
    @RequestWrapper(localName = "BatchSendMail", targetNamespace = "http://soap_alimail/", className = "soap_alimail.BatchSendMail")
    @ResponseWrapper(localName = "BatchSendMailResponse", targetNamespace = "http://soap_alimail/", className = "soap_alimail.BatchSendMailResponse")
    @Action(input = "http://soap_alimail/webservice/BatchSendMailRequest", output = "http://soap_alimail/webservice/BatchSendMailResponse")
    public void batchSendMail();

}
